### ISSUE TITLE
Posting is impossible after the domain change

### ISSUE THREAD

**Issue by 42RK** [wingy/Exodus#18]
After the site moved from 8chan.co to 8ch.net, posting is no longer possible.

**Comment by ZeroTheSavior** [comment]
Seems to work fine for me.

**Comment by w00ly** [comment]
I can't post, nor even browse the site. All I get is a 404 error http://i.imgur.com/Xzdvpc7.png

**Comment by wingy** [comment]
@w00ly version? 0.10 should work fine.
