### ISSUE TITLE
Image thumbnails broken

### ISSUE THREAD

**Issue by Flyingtoast** [wingy/Exodus#20]
Many thumbnails, both on the catalog and within threads, are not loading. Also, for every image that I open that doesn't have a loaded thumbnail, (whether or not the image loads) I get a message that says "Failed to show image".

**Comment by Mommas** [comment]
.

**Comment by Mommas** [comment]
Yeah me too and now I can't comment because I get "error sending reply" message

**Comment by wingy** [comment]
This should have been fixed months ago .
