### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Manizuca** [wingy/Exodus#23]
When i try to build this, if fails because of missing Clover/app/src/main/java/org/wingy/chan/ui/adapter/ThumbListAdapter.java  needed by Clover/app/src/main/java/org/wingy/chan/ui/activity/ImageViewActivity.java (Line 41: import org.wingy.chan.ui.adapter.ThumbListAdapter;)

**Comment by wingy** [comment]
Of course I forgot to add new files to git. Should be fixed as of the latest commit.
